@base_url = https://localhost:7015/api/categoria

### Listar Categorias ###
GET https://localhost:7015/api/categoria/listar

### Criar Categoria ###
POST {{base_url}}/cadastrar
Content-Type: application/json

{
    "nome": "Mercado"
}
